CREATE TABLE [dbo].[t_Order](
	[OrderID] [int] IDENTITY(1,1) NOT NULL,
	[Customer] [varchar](200) NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[TotalValue] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]